### ISSUE TITLE
要是能发表情，和@人就更好了呢。

### ISSUE THREAD

**Issue by tolerious** [austin-----/weibo.emacs#25]
如题的呢～～嘿嘿，不知道是不是提这个要求合不合适，嘿嘿

**Comment by xuchunyang** [comment]
写微博时，按`@ TAB `可以补全已经关注的用户。但由于微博 API 的限制，最多只能获得 1/3 的关注量 [1]。

1: http://open.weibo.com/wiki/2/friendships/friends

@austin----- 应该可以关掉这个 issue 了。
