### ISSUE TITLE
Easy walkthrough or link to application page for weibo api key

### ISSUE THREAD

**Issue by academikuser** [austin-----/weibo.emacs#46]
https://www.cs.cmu.edu/~lingwang/weiboguide/

**Comment by academikuser** [comment]
This one is better - Fall 2017
https://china-underground.com/2017/06/14/get-a-weibo-api-key/

Weibo API page (in Chinese)
http://open.weibo.com/development

**Comment by paynito** [comment]
Followed your setup, until I got the app name and app key, 
pasted those over the originals in .emacs.d/elpa/weibo* 
first call to M-x weibo-timeline gives this error in the browser:

    访问出错了！
    你所访问的站点在微博认证失败，请你联系(user-name)或者稍后再试。
    (error:redirect_uri_mismatch) 

Seems that I'm missing one more config var.  

    *weibo-timeline*   buffer
    微博：a我的关注 i我的微博 @提到我的微博 x提到我的评论 o发出评论 c收到评论 w谁在说
    命令：P发表微博 L查看 T转发 C评论 
    操作：g新消息 r刷新 j下一条 k上一条 h帮助 q退出
    提示：获取更多较早前消息(m)

**Comment by paynito** [comment]
Should `(defconst weibo-authorize-cb-server "weibo.emacs.cb")`
be changed to my app name?   or has the format of
`Weibo-authorize-url`  changed?

**Comment by paynito** [comment]
http://open.weibo.com/wiki/授权机制说明
suggests
https://api.weibo.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&response_type=code&redirect_uri=YOUR_REGISTERED_REDIRECT_URI

where do I find my registered redirect URI (on open.weibo) and set it (in Weibo-authorize.el) ?

**Comment by paynito** [comment]
Using the 2nd form of the api you give.
`https://api.weibo.com/oauth2/access_token?client_id=4268636932&client_secret=74bdc72b1b285c6c506a5d1abb0ab34c&grant_type=authorization_code&redirect_uri=http://127.0.0.1:42012/`
I get this error in the browser:
`{"error":"HTTP METHOD is not suported for this request!","error_code":10021,"request":"/oauth2/access_token"}`
